name: CI

on:
  push:
    branches: [production]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Dependencies
        working-directory: ./
        run: yarn

      - name: Build homepage
        working-directory: ./
        run: yarn predeploy

      - name: Deploy homepage
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          enable_jekyll: false
