name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install node_modules
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
          
      - name: Build homepage
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: predeploy

      - name: Deploy homepage
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          enable_jekyll: false
